name: drupal9-lando-multisite
recipe: drupal9
config:
  webroot: web
  php: '8.0'
  # composer_version: '2.4.3'
  via: nginx
  drush: true
  xdebug: true

proxy:
  appserver_nginx:
    - main.drupal9test.com
    - site1.drupal9test.com
    - site2.drupal9test.com

services:
  # Database service used for main site.
  database:
    type: mariadb
    portforward: true
    creds:
      user: drupal
      password: drupal
      database: multisite_main

  # Database service used for site1 site.
  site1_db:
    type: mariadb
    portforward: true
    creds:
      user: drupal
      password: drupal
      database: multisite_site1

  # Database service used for site2 site.
  site2_db:
    type: mariadb
    portforward: true
    creds:
      user: drupal
      password: drupal
      database: multisite_site2

  db_phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
      - site1_db
      - site2_db
#    environment:
#      - PMA_ARBITRARY=1
#      - PMA_HOSTS=main_db,site1_db,site2_db
